name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    name: Build & push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        uses: Nyffels-Open-Source/github-actions-calver-version-generator@V1.1.0
        with:
          format: 'YYYY.MM.DD'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            nyffels/einvoice-validator:${{ steps.version.outputs.version }}
            nyffels/einvoice-validator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
